name: cuTensor
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10  # Choose the appropriate Python version
  - cmake       # Required for building the project
  - gxx_linux-64  # or gcc_linux-64 if you prefer GCC
  - pybind11    # Pybind11 for creating Python bindings
  - cudatoolkit # Nvidia CUDA Toolkit for GPU support
